### ISSUE TITLE
SEVERE: Problem updating lucene index database

### ISSUE THREAD

**Issue by piotr-g** [oracle/opengrok#1181] opened 2016-09-01 08:43 UTC
I'm getting error while creating index database from svn sources (I deleted all data before running opengrok index) and index db is not created:
```
Sep 01, 2016 4:37:07 AM org.opensolaris.opengrok.index.IndexDatabase$2 run
SEVERE: Problem updating lucene index database:
java.lang.NoSuchMethodError: org.apache.lucene.index.IndexWriter.prepareCommit()V
        at org.opensolaris.opengrok.index.IndexDatabase.update(IndexDatabase.java:415)
        at org.opensolaris.opengrok.index.IndexDatabase$2.run(IndexDatabase.java:184)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
Opengrok built from newest sources (last commit d49f6b9cb6b2deb410933a1ce056f50495b9154f from Wed Aug 31 17:37:55 2016 +0200) with universal ctags also built from fresh sources.

**Comment by tarzanek** [comment] 2016-09-01 12:09
do you use OpenGrok script directly from cloned sources after the build is done?
The stack you have basically says that your build is missing a jar, resp. it's not on classpath (there is no "lib" directory next to opengrok.jar)

**Comment by piotr-g** [comment] 2016-09-01 12:34
I use it directly from bash (absolut path is used to call OpenGrok script) with sudo and OPENGROK_FLUSH_RAM_BUFFER_SIZE="-m 128" param. lib subfolder exists in root lib directory with correct libraries (e.g. new lucene lib). When I reverted to the last commit (ab149c6bd90146328f29bc6226c41d690048fc46) before "upgrade lucene db" everything works again.

**Comment by tarzanek** [comment] 2016-09-02 14:27
ok, I will retry with big repository
fwiw - if you svn repository is available, I'd like to try with your repo, too

**Comment by tarzanek** [comment] 2016-09-02 14:28
alt. thing that comes to my mind is, that your lib dir is messy and contains both lucene 6.2 and 6.1 and classloader gets confused ...

**Comment by piotr-g** [comment] 2016-09-05 08:42
I thought the same and in fact it was messy with both versions so I deleted old versions from lib folder and all files and folders from data folder and ran index again and got the same error. Unfortunately  I can't share the sources as it contains proprietary code... And indeed the codebase isn't small.

**Comment by piotr-g** [comment] 2016-09-05 11:52
So historycache and index folders are created in data directory. It's likely failing on creating xref as this folder is not created.

**Comment by tarzanek** [comment] 2016-09-05 16:16
since you cleaned lib, can you clean lib also in workspace and rebuild the sources please?
I'd also love to know why it didn't clean old lucene versions when downloading new ones ... (maven or ant is used?)

**Comment by piotr-g** [comment] 2016-09-06 08:57
Sure, I will do it. I'm using ant (default target). I think that it is not a problem with ant task because I manually copied whole lib dir from dist folder in workspace to the destination lib folder. So it was my mistake that at first I left old lucene libs.

**Comment by piotr-g** [comment] 2016-09-06 09:07
You were right. ant default task doesn't clean libs in dist/lib folder. I'm switching to
$ ant clean
$ ant
Maybe using newest universal-ctags is a problem? I'm still getting warnings like "ctags: Warning: Language "clojure" already defined" and similar while indexing.

**Comment by tarzanek** [comment] 2016-09-07 04:45
that warning is ok
ant default will clean libs when it tries to download new lucene version
i'd love to know why this code didn't work for you ...
anyways enjoy! :-)
L

**Comment by vladak** [comment] 2023-10-31 15:25
Seems like the original problem was caused by multiple Lucene versions present, hence closing.

**Closed by vladak** 2023-10-31 15:25 UTC
