### ISSUE TITLE
1.4.0 release issue

### ISSUE THREAD

**Issue by shyoshiz** [oracle/opengrok#3184] opened 2020-08-13 09:49 UTC
This is not code issue.

New 1.4.0 is half released not full in the release page.
Please correct.
Thank you.

**Comment by vladak** [comment] 2020-08-17 09:24
I am aware of the issue. This is caused by #3176.

**Comment by vladak** [comment] 2020-08-17 09:26
We need to publish a release with the recently integrated Lucene 8.6.1 anyway so once I fix the above mentioned bug I will trigger new release.

**Comment by vladak** [comment] 2020-08-18 15:34
I was tempted to remove the Maven `verify` step when creating a release however that might lead to a situation where long standing test failures are not solved (which might cause actual problems in the longer run). It is better to keep this self regulation in place.

**Comment by vladak** [comment] 2020-08-21 06:18
fixed by releasing 1.4.1

**Closed by vladak** 2020-08-21 06:18 UTC
Labels: bug, build
