### ISSUE TITLE
in opengrok-0.13-rc7 doing a search for "#if 0" "#if 1" etc - causes error

### ISSUE THREAD

**Issue by ilovemaui** [oracle/opengrok#1379] opened 2017-02-01 20:38 UTC
in new opengrok, when you try to do a search for "#if 0" "#if 1" etc.. it causes an error.. 
There was an error!

null

java.lang.NullPointerException

**Comment by vladak** [comment] 2017-02-02 11:32
Does the message come with a stack trace ? How exactly is the search performed ?

**Comment by ilovemaui** [comment] 2017-02-02 14:43
there was no stack trace. if you simply did a search where you typed into the full search field. you typed "#if 0" or any other number.. but if you typed "#if x" it didn't give this error. something else I noticed, is that sometimes it works. but if you typed "#if a" it would sometimes give this error, and sometimes not. so not sure what is really happening here..

**Comment by vladak** [comment] 2017-02-15 16:19
If you could inspect Tomcat logs when this happens that would be great.

**Comment by ilovemaui** [comment] 2017-02-15 17:28
will check.

**Comment by vladak** [comment] 2021-03-12 09:09
Can't reproduce in the latest, closing. Feel free to reopen if the issue persists.

**Closed by vladak** 2021-03-12 09:09 UTC
