### ISSUE TITLE
Can't find some file in the xref 

### ISSUE THREAD

**Issue by JustSong** [oracle/opengrok#1794] opened 2017-09-30 07:39 UTC
OpenGrok Version: opengrok-1.1-rc11
JDK: Oracle java version "1.8.0_144"
OS: Ubuntu 12.04.5 LTS
Tomcat: Tomcat8

Hi Sirs,

1. I can't find some file in the "xref" but the file exist in the source code folder.

2. If there is the file in the source root directory and we can't find it in the "xref" after OpenGrok index.

Can you provide some solution that I can index some missing file directly?

**Comment by vladak** [comment] 2017-09-30 08:09
What's the filename ? There are certain filenames that are ignored implicitly.

**Comment by JustSong** [comment] 2017-11-20 02:42
Hi vladak,

I found out the reseaon that Opengrok will ignored the file which exist in source root folder.

Ex:
.
└── Opengrok [folder]
    ├── instance [folder]
    ├── opengrok-1.1-rc11 [folder]
    ├── source [folder]
    │          ├──  qt3d  [folder]
    │          │          ├──  LICENSE.FDL.txt  [file]
    │          │          ├──  qt.pro  [file]
    │          ├──  configure.bat  [file]
    │          ├──  configure.json  [file]

The file in source file (configure.bat, configure.json) will not show in 'xref' link.
If the file in sub folder (LICENSE.FDL.txt, qt.pro) , we can see the file in 'xref' link

**Comment by tulinkry** [comment] 2019-02-18 15:48
As I read it now, this is duplicate of #409

**Comment by vladak** [comment] 2019-02-18 16:08
I concur.

**Closed by vladak** 2019-02-18 16:08 UTC
Labels: bug
