### ISSUE TITLE
Tomcat terminating randomly during reindexing for opengrok running on docker with ldap integration

### ISSUE THREAD

**Issue by sanrut01** [oracle/opengrok#3722] opened 2021-09-22 10:31 UTC
**Describe the bug**
Opengrok is running using the latest opengrok docker image and tomcat server.xml and web.xml  is updated to use LDAP integration. Tomcat is running on context /test
LDAP integration is successful and ui prompting auth credentials and API from localhost are accessed without authentication and reindexing is successful.

Upon next few re-indexing randomly after any one of the re-indexing, the tomcat is failing as termination signal is sent.
NOTE: This only happens randomly for one of the re indexing.

We are running on Kubernetes so the pod is auto restarted on failure

ERROR:
`INFO: Refreshing searcher managers to: http://localhost:8080/test/
Sep 21, 2021 7:50:32 PM org.opengrok.indexer.util.Statistics logIt
INFO: Indexer finished (took 33.916 seconds)

Received signal 15
Terminating Tomcat <Popen: returncode: None args: ['/usr/local/tomcat/bin/catalina.sh', 'run']>
Sync done
21-Sep-2021 19:50:32.134 INFO [Thread-12] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
21-Sep-2021 19:50:32.140 INFO [Thread-12] org.apache.catalina.core.StandardService.stopInternal Stopping service [Catalina]
21-Sep-2021 19:50:32.172 INFO [Thread-12] org.opengrok.indexer.configuration.WatchDogService.stop Watchdog stopped
21-Sep-2021 19:50:32.199 SEVERE [ForkJoinPool-330-worker-3] org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2 Could not rebuild suggester
	net.openhft.chronicle.hash.ChronicleHashClosedException: net.openhft.chronicle.map.VanillaChronicleMap closed
		at net.openhft.chronicle.hash.impl.VanillaChronicleHash.throwExceptionIfClosed(VanillaChronicleHash.java:734)
		at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:608)
		at java.base/java.util.concurrent.ConcurrentMap.getOrDefault(ConcurrentMap.java:88)
		at org.opengrok.suggest.popular.impl.chronicle.ChronicleMapAdapter.get(ChronicleMapAdapter.java:62)
		at org.opengrok.suggest.SuggesterProjectData.lambda$getSearchCounts$2(SuggesterProjectData.java:476)
		at org.opengrok.suggest.SuggesterProjectData$WFSTInputIterator.weight(SuggesterProjectData.java:603)
		at org.apache.lucene.search.suggest.SortedInputIterator.sort(SortedInputIterator.java:184)
		at org.apache.lucene.search.suggest.SortedInputIterator.<init>(SortedInputIterator.java:76)
		at org.apache.lucene.search.suggest.SortedInputIterator.<init>(SortedInputIterator.java:62)
		at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup$WFSTInputIterator.<init>(WFSTCompletionLookup.java:273)
		at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup.build(WFSTCompletionLookup.java:115)
		at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:266)
		at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:253)
		at org.opengrok.suggest.SuggesterProjectData.rebuild(SuggesterProjectData.java:238)
		at org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2(Suggester.java:347)
		at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
21-Sep-2021 19:50:32.199 INFO [ForkJoinPool.commonPool-worker-3] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggesters for [TEST_driver] were successfully rebuilt (took 4 seconds)
21-Sep-2021 19:50:32.200 INFO [ForkJoinPool.commonPool-worker-7] org.opengrok.suggest.Suggester.rebuild Rebuilding the following suggesters: [TEST_driver_releases_m_r20p0_01rel0]
21-Sep-2021 19:50:32.202 SEVERE [ForkJoinPool-331-worker-3] org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2 Could not rebuild suggester
	net.openhft.chronicle.hash.ChronicleHashClosedException: net.openhft.chronicle.map.VanillaChronicleMap closed
		at net.openhft.chronicle.hash.impl.VanillaChronicleHash.throwExceptionIfClosed(VanillaChronicleHash.java:734)
		at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:608)
		at java.base/java.util.concurrent.ConcurrentMap.getOrDefault(ConcurrentMap.java:88)
		at org.opengrok.suggest.popular.impl.chronicle.ChronicleMapAdapter.get(ChronicleMapAdapter.java:62)
		at org.opengrok.suggest.SuggesterProjectData.lambda$getSearchCounts$2(SuggesterProjectData.java:476)
		at org.opengrok.suggest.SuggesterProjectData$WFSTInputIterator.weight(SuggesterProjectData.java:603)
		at org.apache.lucene.search.suggest.SortedInputIterator.sort(SortedInputIterator.java:184)
		at org.apache.lucene.search.suggest.SortedInputIterator.<init>(SortedInputIterator.java:76)
		at org.apache.lucene.search.suggest.SortedInputIterator.<init>(SortedInputIterator.java:62)
		at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup$WFSTInputIterator.<init>(WFSTCompletionLookup.java:273)
		at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup.build(WFSTCompletionLookup.java:115)
		at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:266)
		at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:253)
		at org.opengrok.suggest.SuggesterProjectData.rebuild(SuggesterProjectData.java:238)
		at org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2(Suggester.java:347)
		at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
21-Sep-2021 19:50:32.202 INFO [ForkJoinPool.commonPool-worker-7] org.opengrok.suggest.Suggester.shutdownAndAwaitTermination Suggesters for [TEST_driver_releases_m_r20p0_01rel0] were successfully rebuilt (took 0 seconds)
21-Sep-2021 19:50:32.202 INFO [ForkJoinPool.commonPool-worker-5] org.opengrok.suggest.Suggester.rebuild Rebuilding the following suggesters: [TEST_driver_releases_midgard_trunk]
**21-Sep-2021 19:50:32.204 SEVERE [ForkJoinPool-332-worker-3] org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2 Could not rebuild suggester
	net.openhft.chronicle.hash.ChronicleHashClosedException: net.openhft.chronicle.map.VanillaChronicleMap closed**
		at net.openhft.chronicle.hash.impl.VanillaChronicleHash.throwExceptionIfClosed(VanillaChronicleHash.java:734)
		at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:608)
		at java.base/java.util.concurrent.ConcurrentMap.getOrDefault(ConcurrentMap.java:88)
		at org.opengrok.suggest.popular.impl.chronicle.ChronicleMapAdapter.get(ChronicleMapAdapter.java:62)
		at org.opengrok.suggest.SuggesterProjectData.lambda$getSearchCounts$2(SuggesterProjectData.java:476)
		at org.opengrok.suggest.SuggesterProjectData$WFSTInputIterator.weight(SuggesterProjectData.java:603)
		at org.apache.lucene.search.suggest.SortedInputIterator.sort(SortedInputIterator.java:184)
		at org.apache.lucene.search.suggest.SortedInputIterator.<init>(SortedInputIterator.java:76)
		at org.apache.lucene.search.suggest.SortedInputIterator.<init>(SortedInputIterator.java:62)
		at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup$WFSTInputIterator.<init>(WFSTCompletionLookup.java:273)
		at org.apache.lucene.search.suggest.fst.WFSTCompletionLookup.build(WFSTCompletionLookup.java:115)
		at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:266)
		at org.opengrok.suggest.SuggesterProjectData.build(SuggesterProjectData.java:253)
		at org.opengrok.suggest.SuggesterProjectData.rebuild(SuggesterProjectData.java:238)
		at org.opengrok.suggest.Suggester.lambda$getRebuildRunnable$2(Suggester.java:347)
		at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
		at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
		at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
		at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
		at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
		at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

If you provide the exact version of OpenGrok, JDK used, OS(and its version) used and Tomcat(or your webapp server) used it can help to figure out an environment issue.

Latest Open grok image was used.

**To Reproduce**

1. Use official opengrok latest docker image, have LDAP setting integrated whitelist api endpoint to exclude form authentication .

**Expected behavior**
Not expecting the container restarts

**Screenshots**

**Additional context**
tomcat setenv.sh in conatiner:
`# cat $CATALINA_BASE/bin/setenv.sh
JAVA_OPTS="$JAVA_OPTS -server"

# OpenGrok memory boost to cover all-project searches
# (7 MB * 247 projects + 300 MB for cache should be enough)
# 64-bit Java allows for more so let's use 8GB to be on the safe side.
# We might need to allow more for concurrent all-project searches.
JAVA_OPTS="$JAVA_OPTS -Xmx8g"

export JAVA_OPTS
`
Container resource limits
`          resources:
            requests:
              memory: "18Gi"
              cpu: 4
            limits:
              memory: "20Gi"
              cpu: 4`
There are 9 repos each of 3G each

Web.xml config for authentication:

`    <security-constraint>                                                       
        <web-resource-collection>                                               
            <web-resource-name>API endpoints are checked separately by the web app</web-resource-name>
            <url-pattern>/api/*</url-pattern>                                   
        </web-resource-collection>                                              
    </security-constraint>    
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>Logging Area</web-resource-name>
            <description>
                Authentication for registered users.
            </description>
            <url-pattern>/*</url-pattern>
            <http-method>GET</http-method>
            <http-method>POST</http-method>
        </web-resource-collection>`

**Comment by sanrut01** [comment] 2021-09-22 11:02
The next few re-indexers are done without any issues.
`    <security-constraint>                                                       
        <web-resource-collection>                                               
            <web-resource-name>API endpoints are checked separately by the web app</web-resource-name>
            <url-pattern>/api/*</url-pattern>                                   
        </web-resource-collection>                                              
    </security-constraint>    
    <security-constraint>
        <web-resource-collection>
            <web-resource-name>Logging Area</web-resource-name>
            <description>
                Authentication for registered users.
            </description>
            <url-pattern>/*</url-pattern>
            <http-method>GET</http-method>
            <http-method>POST</http-method>
        </web-resource-collection>`

**Comment by santhu3064** [comment] 2021-09-22 20:44
Looks like duplicate of 3650

**Comment by vladak** [comment] 2021-09-23 07:32
> Looks like duplicate of #3650

yep.

**Closed by vladak** 2021-09-23 07:32 UTC
