### ISSUE TITLE
Regression: Submit search using enter key

### ISSUE THREAD

**Issue by stefan-kaltenberger** [oracle/opengrok#3141] opened 2020-05-06 07:11 UTC
**Describe the bug**
I normally use the "enter" key for submitting my search. Since upgrading to the recent 1.3.14 release this doesn't work anymore, as it did with the previous release 1.3.13. The "Search" button still works.

OpenGrok: 1.3.14
Browser: Mozilla Firefox 75.0 (64-bit) / Google Chrome 81.0.4044.122 (64-bit)

**To Reproduce**
Enter a query into the field "Full Search" (or any other field) and press "enter" to execute the search.

**Expected behavior**
The search gets executed and shows the result page.

**Comment by tarzanek** [comment] 2020-05-06 13:28
so it was one of those changes then:
https://github.com/oracle/opengrok/compare/1.3.13...1.3.14
@idodeclare could this be caused by the 1 hit redir code?

**Comment by vladak** [comment] 2020-05-06 13:44
just noticed that too.

**Comment by idodeclare** [comment] 2020-05-06 15:30
@tarzanek , oops it's inadvertent. Let me raise a PR fix.

**Comment by vladak** [comment] 2020-05-07 09:03
fixed via #3143

**Closed by vladak** 2020-05-07 09:03 UTC
Labels: UI, bug

**Comment by stefan-kaltenberger** [comment] 2020-05-07 12:13
Thank you. The release 1.3.15 fixed the issue for me.
