### ISSUE TITLE
.opengrok_skip_history processing needs to happen elsewhere than addRepositories()

### ISSUE THREAD

**Issue by idodeclare** [oracle/opengrok#1799] opened 2017-10-02 22:29 UTC
I have tried out 1.1-rc14 and -rc15, but the Repository list shows only a handful of my 23 repositories  (1 hg, 22 Git) versus the complete Repository list being correctly shown in 1.1-rc13.

I did try a full re-indexing (having deleted data/ and the XML configuration file), but that did not fix things for -rc15.

I then rolled back to -rc13.

**Comment by vladak** [comment] 2017-10-03 08:44
Anything relevant in indexer logs ? Do you use projects ?

**Comment by vladak** [comment] 2017-10-03 08:54
Could you also try diff-ing the XML configuration file produced by 0.13 and 0.14 ?

**Comment by idodeclare** [comment] 2017-10-04 12:51
The XML diff just shows the repos excluded along with the new attribute, "directoryNameRelative".

The excluded repositories have a file, .opengrok_skip_history, at their root.

**Comment by vladak** [comment] 2017-10-04 13:33
I'd say the `directoryNameRelative` is just a noise and not relevant. Looks like the changes for  `.opengrok_skip_history` inba 21c3b2b094479eac7b5236f6312955095c8b94 have undesired side effects,

**Comment by vladak** [comment] 2017-10-04 18:21
I think what happened with the skip history code is that:
  1. comitted, however the algorithm never worked
  2. above mentioned cset fixed it so it started working

The idea of avoiding history by skipping the repositories altogether seems wrong to me. I think the fix should be done somewhere in `HistoryGuru` or `HistoryCache`.

The problem is visible even if projects are enabled. In such case the project with disabled history is not visible in the Repository table however is visible in project picker and searchable.

**Comment by vladak** [comment] 2018-07-30 09:58
I see that the logging was fixed in cset 4550891c.

**Comment by vladak** [comment] 2018-08-14 14:08
This was fixed in cset 2b892162 (for #1728).

**Closed by vladak** 2018-08-14 14:08 UTC
Labels: bug, stopper
