### ISSUE TITLE
Search result with only one hit should be shown directly (Bugzilla #12903)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#423] opened 2013-05-22 07:04 UTC
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Trond Norbye

On 2009-11-26 09:50:36 +0000, Frank Mau wrote:

> Title:
> Search result with only one result/hit should be shown directly
> 
> Description:
> Curent situation...
> - Making a search in the web-front-end
> - Getting only one result list
> - Click on result-link
> - Show data
> 
> Disadvantage:
> Have one not-needed click
> 
> Please support direct opening of one-result search, thanks. Usability issue

**Comment by tulinkry** [comment] 2019-02-03 19:54
duplicate of #1984

**Closed** 2019-02-04 07:22 UTC
Labels: enhancement
