### ISSUE TITLE
OpenGrok does not jump to specific line when #line added (chrome only)

### ISSUE THREAD

**Issue by yilangli** [oracle/opengrok#3182] opened 2020-08-10 18:23 UTC
**Describe the bug**
I'm using java openjdk 1.8.0_232, tomcat8.0.21, openGrok 0.12.1, Linux 2.6.32-431.11.2.el6.x86_64 x86_64.

It was working correctly. few months before, Opening the source page always navigate to the start of page when #line added to the link. for example: www.github.com/hello_world.h#999, it will not navigate to line 999 but to the head of hello_world.h file. and this symptom only happens to Chrome. firefox and IE works correctly.

**Expected behavior**
expect to jump the specific line when #line added.

**Comment by vladak** [comment] 2020-08-18 16:15
Perhaps similar to #3159

**Comment by ahornace** [comment] 2021-03-03 17:45
Closing as duplicate of https://github.com/oracle/opengrok/issues/3159

**Closed by ahornace** 2021-03-03 17:45 UTC
Labels: UI
