### ISSUE TITLE
repository not displayed on the index page on Windows

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#2335] opened 2018-09-03 08:28 UTC
As reported in #2315, after the changes in csets b2315481a20b1e8658027d7ded7e38e3b017fdce or 31256c90e23def96ac9b26214b043921cf804c84 the repositories stopped appearing on the index page on Windows.

**Comment by tarzanek** [comment] 2018-09-04 14:33
I will try with git, 
I might have perforce around too, but I doubt I can get it up (I will give it a try if git will work).

**Comment by tarzanek** [comment] 2018-09-20 06:12
ok, got the problem reproduced
reason really is the path, e.g. : 
"08:04:30 WARNING: Couldn't find a start term for \OpenGrok , empty u field? "

the index won't really get populated, so indexing on windows defacto isn't working

**Comment by vladak** [comment] 2018-09-26 16:06
Looks like the change I did in cset b2315481 in `populateDocument()` to sanitize path was not enough. Maybe I should've used `replaceAll()` ?

**Comment by tarzanek** [comment] 2018-09-27 06:02
got a fix for the indexing problem on windows, but repos still don't show, it seems that when no groups are defined, no repos will be printed out
- I thought that some default group is still there and the projects will be printed out as part of it, did that change? @vladak @Orviss ?

**Comment by tarzanek** [comment] 2018-09-27 06:06
@gtoph so I see the same as you and not sure where the behaviour is coming from
gtoph wrote: " Gave it a 5 min debug. in repos.jspf, repositories are returning zero for some reason from this:

Set<Project> repositories = pHelper.getUngroupedRepositories(); "

**Comment by gtoph** [comment] 2018-09-27 21:15
Pulled in your change, seems to work fine now.  Perforce repo shows up on the main main page, and xref links work.  Ship it :)

**Comment by vladak** [comment] 2018-09-28 16:29
@gtoph I see that you got Perforce working, could you maybe comment in #2358

**Comment by tarzanek** [comment] 2018-09-30 15:41
I guess I will need to do more cleanup based on Vladas comments

**Comment by tarzanek** [comment] 2018-10-03 05:02
ok, let's fix appveryor build before I will push this

**Comment by gtoph** [comment] 2018-10-04 19:44
Just to add, and I'm still trying to verify it, but when I go to re-index it's doing the entire project over, rather than recognize just the changed files like it used to.   Was trying to find where in the code it checks that, but wasn't sure yet.  Wonder if there is a path mis-match that is throwing that logic off.

Anywho, just to make sure of the behavior, I have it indexing right now, and when it finished, i'm going to just try doing it again and I would expect it to just blow right through it without doing much of anything.

**Comment by tarzanek** [comment] 2018-10-05 13:47
ok, so it means the uuids are broken exactly as Vlada suggested
so I need to fix it, it's surprising, that the incremental reindex check passed, most probably because the index happened again from scratch, so the test needs some improvements ...

**Comment by gtoph** [comment] 2018-10-31 17:55
@tarzanek I merged in your latest fork into my master branch pull, and it seems to be working much better thus far.  Haven't done extensive testing yet, but previously, it would reindex every file even if untouched, and I would see every file duplicated in the search results page.  Both those look fixed now.

**Closed** 2018-11-06 15:32 UTC
Labels: bug, stopper
