### ISSUE TITLE
use POST and not GET

### ISSUE THREAD

**Issue by dhireng** [oracle/opengrok#1048] opened 2016-02-02 09:01 UTC
Can the application be changed to use POST and not GET. The issue I'm seeing is that URI's are lengthy and some browsers not seem to like it.

**Comment by tarzanek** [comment] 2016-02-02 10:06
which browsers? :)
the url is intentional - reason is simple, sharing of pointers to code ...

**Comment by dhireng** [comment] 2016-02-02 10:11
I was reading up http://www.boutell.com/newfaq/misc/urllength.html and  
> Extremely long URLs are usually a mistake. URLs over 2,000 characters will not work in the most popular web browser.

I get loads of security errors on firefox and chrome and my network guys don't even see a hit on the network when this happens.

**Comment by tarzanek** [comment] 2016-02-02 14:08
well your url won't be long unless you do search over all projects
and this is perhaps the only place where I'd optimize to POST
I think we might have had even a pull req for that (but don't remember), but surely there is the space for improvement for that query
All other queries rarely go over 2000 chars

**Comment by tarzanek** [comment] 2016-02-02 14:09
note the DOCs on tomcat tuning for long urls ...

**Comment by dhireng** [comment] 2016-02-09 09:55
okay. I've been breaking my head with a long query string for a while now. The problem I faced is that if i search on all projects, I got results. But when I searched again without changing any condition, I always got an error if I use a BIG-IP F5 load balancer. After using the developer tools in Firefox, figured that the HTTPRefer is very long that the load balancer did not like it or a device infront of it did not like it.
Finally I added the line <meta name="referrer" content="no-referrer" /> to my header jsp and it all works okay now. 
Do you see any value out of the referer? or can we include it in the base?

**Comment by tarzanek** [comment] 2016-02-10 11:51
hmm, I have some doubts, it will definitely break e.g. SSO logins ... @vladak  ?

**Comment by vladak** [comment] 2016-03-04 12:50
anyone has a code which I can try ? What about compressing the list of projects ?

**Comment by rahul-chhabra** [comment] 2016-05-26 21:55
I have question on same topic. I have multiple small repos, more than 1000. Currently I am testing with 50 and Opengrok is working great. However, I am anticipating with 1000 projects it will break everytime in GET request when done on all projects. 
Is there already way to configure it to POST, so i can avoid this issue ?

**Comment by tarzanek** [comment] 2016-05-27 15:28
@rahul-chhabra 
https://github.com/OpenGrok/OpenGrok/blob/master/README.txt#L936

**Comment by rahul-chhabra** [comment] 2016-05-27 22:16
Thanks @tarzanek for quick response. Really appreciate it.
I will slowly scale up number of repos in opengrok and will increase this maxHttpHeaderSize value in tomcat. Will let know, if faces any issue.

Cheers.

**Comment by tulinkry** [comment] 2019-02-03 13:17
Seems the problem is resolved.

**Comment by vladak** [comment] 2019-02-03 16:32
Closing as a dup of #1357 and also #2518

**Closed by vladak** 2019-02-03 16:32 UTC
