### ISSUE TITLE
Index database(s) not found in OpenGrok for a particular repository.

### ISSUE THREAD

**Issue by avnish-sharma** [oracle/opengrok#3418] opened 2021-02-11 04:34 UTC
Facing an issue 'Index database(s) not found.' in OpenGrok for a particular repository. Issue persists post index recreation.

**Comment by vladak** [comment] 2021-02-11 09:34
How do you run the indexer exactly ? Could you post the configuration here ? (ideally extracted from the web app using http://localhost:8080/source/api/v1/configuration - assuming the name of the application is `source`) For which project does this happen ?

**Comment by vladak** [comment] 2021-02-11 09:36
I think this error usually happens if the source root is mis-configured (which is probably not your case as this happens only for some projects) or might happen if the project is not marked as indexed.

**Comment by vladak** [comment] 2021-02-11 09:39
Maybe the web app should emit more detailed error message. After all, there is a commented out line in the code: https://github.com/oracle/opengrok/blob/876391fae90ef7239a29b98c01205b3ab9a89fcc/opengrok-indexer/src/main/java/org/opengrok/indexer/web/SearchHelper.java#L346-L348

**Comment by avnish-sharma** [comment] 2021-02-15 12:50
> How do you run the indexer exactly ? Could you post the configuration here ? (ideally extracted from the web app using http://localhost:8080/source/api/v1/configuration - assuming the name of the application is `source`) For which project does this happen ?

we are executing the indexer like : 
/scratch/ofssobp/jdk-11.0.3/bin/java -Xms2048m -Xmx4096m -XX:-UseCompressedOops -Dorg.opensolaris.opengrok.history.cvs=cvs -Dorg.opensolaris.opengrok.history.Subversion=svn -Djava.util.logging.config.file=/scratch/opengrok_setup/opengrok/data/logging.properties -jar /scratch/opengrok_setup/opengrok/lib/opengrok.jar -c ctags -W /scratch/opengrok_setup/opengrok/data/configuration.xml -P -S -r on -v -U localhost:8080 -s /scratch/opengrok_setup/opengrok/src -d /scratch/opengrok_setup/opengrok/data

**Comment by vladak** [comment] 2021-02-15 13:33
Okay, that looks normal. If you go to the `/scratch/opengrok_setup/opengrok/data/index` directory, is there a subdirectory matching the name of the project exhibiting the failure ? If yes, what is inside this directory ? What are the permissions of this directory and the files therein ?

**Comment by vladak** [comment] 2021-02-15 13:50
Is there any related log messages in Tomcat logs ?

**Comment by vladak** [comment] 2021-02-15 13:54
In order to reproduce this, I restricted the permissions of index directory for particular project and later also moved it away however this ended up with the `Failed to initialize search. Check the index for projects` error message because `getMultiReader()` returned `null` (and properly logged this so that this was visible in Tomcat log).

**Comment by avnish-sharma** [comment] 2021-02-15 14:11
> Okay, that looks normal. If you go to the `/scratch/opengrok_setup/opengrok/data/index` directory, is there a subdirectory matching the name of the project exhibiting the failure ? If yes, what is inside this directory ? What are the permissions of this directory and the files therein ?

yes, there is a project name matching subdirectory, containing 3 files: segments_5, _31.cfs and segments.gen.  Sometimes 4th file also gets generated.
Subfolder has permissions rwxr-xr-x / (Octal mode 755) and 3 files has rw-r--r--  (Octal Mode 644).

**Comment by vladak** [comment] 2021-02-15 15:41
Compare this to the index directory contents corresponding to the working projects.

**Comment by vladak** [comment] 2021-02-15 17:14
This looks like unfinished indexing of this particular project. Normally the `index` directory for a project contains stuff such as:
```
-rw-rw-r-- 1 foo foo     157 Feb 15 16:45 _40.fdm
-rw-rw-r-- 1 foo foo 1824131 Feb 15 16:45 _40.fdt
-rw-rw-r-- 1 foo foo     103 Feb 15 16:45 _40.fdx
-rw-rw-r-- 1 foo foo    1502 Feb 15 16:45 _40.fnm
-rw-rw-r-- 1 foo foo   37116 Feb 15 16:45 _40.nvd
-rw-rw-r-- 1 foo foo     427 Feb 15 16:45 _40.nvm
-rw-rw-r-- 1 foo foo     655 Feb 15 16:45 _40.si
-rw-rw-r-- 1 foo foo  137495 Feb 15 16:45 _40.tvd
-rw-rw-r-- 1 foo foo     161 Feb 15 16:45 _40.tvm
-rw-rw-r-- 1 foo foo     201 Feb 15 16:45 _40.tvx
-rw-rw-r-- 1 foo foo   48226 Feb 15 16:45 _40_Lucene80_0.dvd
-rw-rw-r-- 1 foo foo     418 Feb 15 16:45 _40_Lucene80_0.dvm
-rw-rw-r-- 1 foo foo  916454 Feb 15 16:45 _40_Lucene84_0.doc
-rw-rw-r-- 1 foo foo 1947375 Feb 15 16:45 _40_Lucene84_0.pay
-rw-rw-r-- 1 foo foo 5468770 Feb 15 16:45 _40_Lucene84_0.pos
-rw-rw-r-- 1 foo foo  988052 Feb 15 16:45 _40_Lucene84_0.tim
-rw-rw-r-- 1 foo foo   19205 Feb 15 16:45 _40_Lucene84_0.tip
-rw-rw-r-- 1 foo foo    1325 Feb 15 16:45 _40_Lucene84_0.tmd
-rw-rw-r-- 1 foo foo     157 Feb 15 16:45 segments_1f
```

Could you check the indexer logs ?

**Comment by vladak** [comment] 2021-02-16 08:30
The strange thing about this is that the web app should only provide projects to the user that are indexed. Could you get the output from http://localhost:8080/source/api/v1/projects/INSERT_YOUR_PROJECT_NAME_HERE/property/indexed ?

**Comment by avnish-sharma** [comment] 2021-02-16 14:26
found this error in tomcat file catalina.2021-02-15.log :
15-Feb-2021 10:03:03.908 INFO [http-nio-8080-exec-4] org.opensolaris.opengrok.web.PageConfig.getEftarReader Failed to create EftarFileReader:
        java.io.FileNotFoundException: /var/opengrok/data/index/dtags.eftar (No such file or directory)
                at java.io.RandomAccessFile.open0(Native Method)
                at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
                at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
                at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124)
                at org.opensolaris.opengrok.web.EftarFileReader.<init>(EftarFileReader.java:138)
                at org.opensolaris.opengrok.web.PageConfig.getEftarReader(PageConfig.java:477)
                at org.opensolaris.opengrok.web.PageConfig.prepareSearch(PageConfig.java:1124)

**Comment by vladak** [comment] 2021-02-17 08:08
This exception most likely correlates to the changes in 0b77b425 and is unrelated. Anyway, that's from the web app log. You need to find out why the project was not fully indexed. I'd suggest to take a look into the indexer logs.

**Comment by vladak** [comment] 2021-02-17 08:09
Thinking of this, maybe we should have a concept of de-indexing a project, i.e. marking its `indexed` property as false on the basis of failures such as the one described in this issue.

**Comment by vladak** [comment] 2021-02-17 09:42
When working on the above pull request I realized the index might be just old, i.e. produced with indexer that is incompatible with the web application.

**Comment by vladak** [comment] 2021-02-17 16:01
Try upgrading to OpenGrok 1.5.12.

**Comment by vladak** [comment] 2021-03-09 13:11
closing as stale, feel free to reopen.

**Closed by vladak** 2021-03-09 13:11 UTC
Labels: indexer, question
