### ISSUE TITLE
click the "history" link NullPointerException

### ISSUE THREAD

**Issue by mmh891113** [oracle/opengrok#3211] opened 2020-09-04 08:59 UTC
**Describe the bug**
when click the "history" link show the NullPointerException error.

```
There was an error!

null

java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at org.opengrok.indexer.web.PageConfig.getShortPath(PageConfig.java:1609)
	at org.opengrok.indexer.web.PageConfig.getHistoryTitle(PageConfig.java:1672)
	at org.apache.jsp.history_jsp._jspService(history_jsp.java:196)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:477)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.ResponseHeaderFilter.doFilter(ResponseHeaderFilter.java:42)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.StatisticsFilter.doFilter(StatisticsFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.AuthorizationFilter.doFilter(AuthorizationFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.opengrok.web.LoginFilter.doFilter(LoginFilter.java:95)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I search the source code , **found that  the path variable is null,**  in src/main/java/org/opengrok/indexer/web/PageConfig.java 
 getShortPath(String path)

```
    public String getShortPath(String path) {
        File file = new File(path);

        if (path.isEmpty()) {
            return "/";
        }

        return file.getName();
    }
```

then I add some check, like below:
```
    public String getShortPath(String path) {
       if(path == null) {
           return "/";
       }
        File file = new File(path);

        if (path.isEmpty()) {
            return "/";
        }

        return file.getName();
    }
```
then the history link work...   This is a bug ?? or  What's wrong with my configuration that causes this path variable to be null ?

**To Reproduce**

**Expected behavior**

**Screenshots**
![1](https://user-images.githubusercontent.com/16930340/92221133-95f93680-eecf-11ea-931d-544680aa8658.png)

**Additional context**

**Comment by vladak** [comment] 2020-09-04 17:49
what OpenGrok version are you running ?

**Comment by vladak** [comment] 2020-09-04 17:52
Perhaps `getHistoryTitle()` should call `getPath()`.

**Comment by mmh891113** [comment] 2020-09-09 07:59
may be this issue was fixed.  i try version 1.4.2 , there is no this issue.
```

in AuthorizationFilter.java 
        PageConfig config = PageConfig.get(httpReq);
        long processTime = System.currentTimeMillis();

        Project p = config.getProject();

--> config.getProject();
 --> getResourceFile()

the path  will be init in method  getResourceFile () in getPath()

    public File getResourceFile() {
        if (resourceFile == null) {
            resourceFile = getResourceFile(getPath());
            if (resourceFile == null) {
                resourceFile = new File(PATH_SEPARATOR_STRING);
            }
        }
        return resourceFile;
    }
```

**Comment by vladak** [comment] 2020-09-09 08:02
Could be caused by timing/ordering. Anyway, once the PR listed above merges in this will be fixed for good.

**Comment by vladak** [comment] 2020-09-11 06:50
Once 1.4.3 ships please give it a try so this can be eventually closed.

**Comment by vladak** [comment] 2020-09-15 18:59
1.4.3 is out now, please give it a try.

**Comment by mmh891113** [comment] 2020-09-21 23:14
I upgraded to 1.4.3，The issue seems to be solved, thanks vladak.

**Comment by vladak** [comment] 2020-09-22 06:56
cool.

**Closed by vladak** 2020-09-22 06:56 UTC
Labels: UI, bug
