### ISSUE TITLE
Suggester not working

### ISSUE THREAD

**Issue by chkp-baselz** [oracle/opengrok#3684] opened 2021-07-28 10:50 UTC
Hey :)

Suggester suddenly not working, found several like this in log
`28-Jul-2021 05:08:10.052 SEVERE [ForkJoinPool-736-worker-31] org.opengrok.suggest.Suggester.lambda$getInitRunnable$1 Could not initialize suggester data for baratol
        java.io.IOException: Could not create suggester directory /opengrok/data/suggester/baratol
                at org.opengrok.suggest.SuggesterProjectData.createSuggesterDir(SuggesterProjectData.java:282)
                at org.opengrok.suggest.SuggesterProjectData.init(SuggesterProjectData.java:153)
                at org.opengrok.suggest.Suggester.lambda$getInitRunnable$1(Suggester.java:229)
                at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
                at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
                at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
                at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
                at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
                at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)`

**Comment by ahornace** [comment] 2021-07-28 11:03
Closing as duplicate of https://github.com/oracle/opengrok/issues/3668

Not sure why we are seeing more issues like this recently. Maybe the package manager changed the user tomcat uses?

**Closed by ahornace** 2021-07-28 11:03 UTC

**Comment by vladak** [comment] 2021-07-28 12:05
It this happening using standalone Tomcat or are you using the official Docker image ?
