### ISSUE TITLE
Cannot create opengrok groups in version 1.12.11

### ISSUE THREAD

**Issue by tarangchikhalia** [oracle/opengrok#4382] opened 2023-07-06 14:52 UTC
**Describe the bug**
We use opengrok-groups script to create groups of projects in our opengrok instance. After upgrading to version 1.12.11, the script seems to run without error but readonly_configuration.xml file is not updated with new groups

OpenGrok version: 1.12.11
JDK: 11
OS: Oracle Linux 8.6
Tomcat: 10.1.8

**To Reproduce**
Run opengrok-groups to create new readonly_configuration.xml file

`opengrok-groups --java "${JAVA_HOME}/bin/java" --jar "${OPENGROK_INSTANCE_BASE}/lib/opengrok.jar" -- -e > "${OPENGROK_INSTANCE_BASE}/readonly_configuration.xml"`

Output of readonly_configuration.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<java version="11.0.18" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
  <void id="SuggesterConfig0" property="suggesterConfig">
   <void property="allowedFields">
    <void method="clear"/>
    <void method="add">
     <string>defs</string>
    </void>
    <void method="add">
     <string>path</string>
    </void>
    <void method="add">
     <string>hist</string>
    </void>
    <void method="add">
     <string>refs</string>
    </void>
    <void method="add">
     <string>type</string>
    </void>
    <void method="add">
     <string>full</string>
    </void>
   </void>
  </void>
 </object>
</java>
```

Add a new group:

`opengrok-groups  --java "${JAVA_HOME}/bin/java" --jar "${OPENGROK_INSTANCE_BASE}/lib/opengrok.jar" -- -i "${OPENGROK_INSTANCE_BASE}/readonly_configuration.xml" -n "GEMS" -r "GEMS_*" -o /var/opt/opengrok/main/etc/readonly_configuration_new.xml`

Output of readonly_configuration_new.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<java version="11.0.18" class="java.beans.XMLDecoder">
 <object class="org.opengrok.indexer.configuration.Configuration" id="Configuration0">
  <void id="SuggesterConfig0" property="suggesterConfig">
   <void property="allowedFields">
    <void method="clear"/>
    <void method="add">
     <string>defs</string>
    </void>
    <void method="add">
     <string>path</string>
    </void>
    <void method="add">
     <string>hist</string>
    </void>
    <void method="add">
     <string>refs</string>
    </void>
    <void method="add">
     <string>type</string>
    </void>
    <void method="add">
     <string>full</string>
    </void>
   </void>
  </void>
 </object>
</java>
```

**Expected behavior**
group should be created in the readonly_configuration.xml file

**Screenshots**
NA

**Additional context**
NA

**Comment by vladak** [comment] 2023-07-09 21:13
I think this is caused by the conversion of the groups from set to map (#4306).

**Comment by vladak** [comment] 2023-07-10 19:11
> @vladak, Is there any step I can take right now to resolve this or we need code change?

This has to be fixed in code.

**Closed** 2023-07-11 18:43 UTC
Labels: bug
