### ISSUE TITLE
Search should be able to look only on specific type of object (Bugzilla #19048)

### ISSUE THREAD

**Issue by vladak** [oracle/opengrok#520] opened 2013-05-22 07:06 UTC
status NEW severity _enhancement_ in component _webapp_ for _---_
Reported in version _unspecified_ on platform _ANY/Generic_
Assigned to: Lubos Kosco

On 2011-11-04 11:41:24 +0000, Zdenek Kotala wrote:

> It would be nice if I could specify what kind of definition I'm looking for. For example when I try to find msg() function it shows me also bunch of char *msg; results and so on.

**Comment by tulinkry** [comment] 2019-02-03 13:06
Duplicate of #685 and can be closed.

**Closed** 2019-02-03 16:37 UTC
Labels: enhancement
