### ISSUE TITLE
opengrok does't jump with function name with prefix "__" in C language

### ISSUE THREAD

**Issue by cheneydeng** [oracle/opengrok#1296] opened 2016-12-05 12:00 UTC
hi guys,
   I'm using OpenGrok to read one project which written with C language,everything is perfect except the function name with "__" as prefix will not jump to the definition when clicked.I read the html code and find that the marker has no "name" item with such functions.How can i fix it quickly as I'm really rely on OpenGrok.Thanks as advance.

**Comment by vladak** [comment] 2016-12-05 12:07
What ctags implementation (+version) do you use ?

**Comment by cheneydeng** [comment] 2016-12-05 12:10
@vladak This is my ctags version:

`
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 13 2015, 03:28:50
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
`

**Comment by vladak** [comment] 2016-12-05 12:52
and OpenGrok version ?

One thing you can try is to replace Exuberant ctags with Universal ctags ?

Also, could you try to isolate the issue by shortening the file to smallest possible size where the problem still occurs ?

**Comment by tulinkry** [comment] 2016-12-05 14:18
0.13-RC5
[main.c.txt](https://github.com/OpenGrok/OpenGrok/files/631307/main.c.txt)

**Comment by tulinkry** [comment] 2016-12-05 14:33
The problem is here: [JFlexXref.java#L577-L587](https://github.com/OpenGrok/OpenGrok/blob/7ae7d63284bc15a7584a62552ceeea7f6a4f01a6/src/org/opensolaris/opengrok/analysis/JFlexXref.java#L577-L587)

**Comment by cheneydeng** [comment] 2016-12-06 02:25
@tulinkry @vladak Thanks for your reply.I've modified the code and rebuild it,when deploy it said:

> ➜  OpenGrok git:(master) ✗ OPENGROK_TOMCAT_BASE=/usr/local/Cellar/tomcat/8.5.3/libexec ./OpenGrok deploy
Loading the default instance configuration ...
Installing /Users/cheneydeng/software/OpenGrok/dist/source.war to /usr/local/Cellar/tomcat/8.5.3/libexec/webapps ...

> Start your application server (Tomcat),  if it is not already
  running, or wait until it loads the just installed web  application.

> OpenGrok should be available on <HOST>:<PORT>/source
  where HOST and PORT are configured in Tomcat.

Actually my tomcat is running on localhost:8080 as before so i restarted tomcat and found my modification seems not works,maybe the deploy failed?

**Comment by cheneydeng** [comment] 2016-12-07 09:30
@tulinkry the modification works.thanks so much

**Comment by vladak** [comment] 2016-12-07 09:45
Still needs to be fixed in master ?

**Comment by harryxp** [comment] 2018-04-10 05:35
I'd like to fix this in the next release.  The quick fix proposed by @tulinkry still works, although that piece of regex has been moved to JFlexXrefUtils.java.

Since it's called a quick fix I assume there's a more proper way to do it?  Can someone give me a hint and I'm happy to do a PR.

**Comment by idodeclare** [comment] 2018-04-10 21:49
I have a queued-up patch, "Use HTML5 DOCTYPE, as XHTML was not at all confirming anyway" (9ebda741e), that also integrated @tulinkry 's advice w.r.t. the name matching.

**Closed** 2018-04-17 20:48 UTC
Labels: bug
